using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace COMP123_MidTermExam
{
    /**
     * <summary>
     * This class is a subclass of the LottoGame abstract superclass
     * </summary>
     * 
     * @class Lotto649
     */
    public class Lotto649 : LottoGame, IGenerateLottoNumbers
    {
        // CONSTRUCTORS ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

        /**
         * <summary>
         * This constructor does not take any parameters but satisfies the
         * base constructor requirements by send the elementNumber and setSize
         * </summary>
         * 
         * @constructor
         */
        public Lotto649()
            : base(6, 49)
        {

        }

        // CREATE the public GenerateLottoNumbers method here ----------------
        
        /**
         * <summary>
         * This public method calls the Pickelements method
         * it display the random number generated by using Tostring() method of abstract class
         * </summary>
         * 
         * @method
         */
        public void GenerateLottoNumbers()
        {
            for (int i = 1; i <= ElementNumber; i++)
            {
                PickElements(); //calling pick Elements to generate random numbers
                Console.Write($"ticket{ i } :");
                Console.WriteLine(ToString());
                
            }
        }
           


        }
        

        
    }

